/**
 * @37bytes/code-style — Biome configuration
 *
 * Biome v2 configuration mirroring our ESLint ruleset.
 * Generated by `node biome/build.js` from modular rule files.
 *
 * ## Consumer usage
 *
 * In consumer's biome.json:
 * ```json
 * {
 *   "extends": ["@37bytes/code-style/biome"]
 * }
 * ```
 *
 * ## What Biome covers
 *
 * ~125 rules from ESLint core, TypeScript, React, Next.js, imports, sonarjs.
 * Includes nursery type-aware rules (noFloatingPromises, noMisusedPromises).
 * Biome domains auto-activate based on consumer's package.json deps.
 *
 * ## What stays ESLint-only
 *
 * - @37bytes/* custom rules (boolean-naming, no-arrow-props, no-storage, enum-pattern)
 * - eslint-plugin-regexp (61 rules)
 * - eslint-plugin-sonarjs (18 of 20 rules)
 * - eslint-plugin-storybook (14 rules)
 * - eslint-plugin-perfectionist (11 rules)
 * - eslint-plugin-n (33 of 34 rules)
 * - react-compiler rules (15 rules)
 * - testing-library + jest-dom (19 rules)
 * - Most unicorn rules (~60 of 80)
 *
 * ## Hybrid mode (Biome + ESLint)
 *
 * Use eslint-config-biome to disable ESLint rules covered by Biome:
 * ```js
 * // eslint.config.mjs
 * import biome from 'eslint-config-biome';
 * export default [...yourConfigs, biome];
 * ```
 *
 * Note: eslint-config-biome is static (doesn't read biome.json).
 * Manual overrides may be needed for non-recommended rules.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export const config = JSON.parse(readFileSync(join(import.meta.dirname, './config.json'), 'utf8'));
