/**
 * @fileoverview Core JavaScript rules for OxLint
 *
 * ESLint core + promise + unicorn (non-DOM, non-import subset).
 * Maps to eslint/rules/javascript.js.
 */

export const javascript = {
    // === Syntax & Logic ===
    curly: 'error',
    eqeqeq: ['warn', 'smart'],
    'no-console': 'error',
    'no-debugger': 'error',
    'no-alert': 'error',
    'no-empty': 'error',
    'no-else-return': 'warn',
    'no-extra-boolean-cast': ['error', { enforceForLogicalOperands: true }],
    'no-var': 'error',
    'no-self-compare': 'error',
    'no-useless-return': 'error',
    'no-implicit-coercion': ['error', { boolean: true, number: true, string: true }],
    'default-case': ['error', { commentPattern: '^no default$' }],
    'default-case-last': 'error',
    'prefer-template': 'warn',
    'no-nested-ternary': 'error',
    // camelcase — not available in OxLint, stays ESLint-only
    'array-callback-return': 'error',
    'no-caller': 'warn',
    'no-new-func': 'warn',
    'no-new-wrappers': 'warn',
    'no-cond-assign': ['warn', 'except-parens'],
    'no-fallthrough': 'warn',
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
    'no-extra-label': 'warn',
    'no-label-var': 'warn',
    'no-sequences': 'warn',
    'prefer-const': ['warn', { destructuring: 'any' }],
    'no-const-assign': 'error',
    'no-delete-var': 'warn',
    'no-global-assign': 'warn',
    'no-shadow-restricted-names': 'warn',
    'no-undef': 'error',
    'no-unused-vars': ['warn', { args: 'none', ignoreRestSiblings: true }],
    'no-use-before-define': ['warn', { functions: false, classes: true, variables: true }],
    'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
    'no-unused-labels': 'warn',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',

    // === Security ===
    'no-eval': 'error',
    // no-implied-eval — in OxLint as typescript/no-implied-eval (see typescript.js)
    'no-script-url': 'warn',

    // === Anti-patterns ===
    'no-extend-native': 'warn',
    'no-iterator': 'warn',
    'no-with': 'warn',
    'no-proto': 'warn',
    'no-empty-pattern': 'warn',
    'no-sparse-arrays': 'warn',
    'no-extra-bind': 'warn',
    'no-func-assign': 'error',
    'no-ex-assign': 'warn',
    'no-obj-calls': 'error',
    'no-self-assign': 'warn',
    'getter-return': 'error',
    'no-multi-str': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-escape': 'warn',
    'no-this-before-super': 'warn',
    'no-useless-constructor': 'warn',
    'no-throw-literal': 'warn',
    'no-unreachable': 'error',
    'no-useless-computed-key': 'warn',
    'no-useless-rename': ['warn', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
    'no-unsafe-negation': 'warn',
    'use-isnan': 'error',
    'valid-typeof': 'error',

    // === Async ===
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'warn',
    'no-promise-executor-return': 'error',
    'require-yield': 'warn',

    // === Misc ===
    'no-regex-spaces': 'warn',
    'unicode-bom': ['warn', 'never'],

    // === Promise ===
    'promise/prefer-await-to-then': 'warn',
    'promise/no-return-in-finally': 'error',
    'promise/no-multiple-resolved': 'error',
    'promise/no-callback-in-promise': 'warn',
    'promise/spec-only': 'error',

    // === Unicorn (non-DOM, non-import) ===
    'unicorn/catch-error-name': 'warn',
    'unicorn/consistent-assert': 'error',
    'unicorn/consistent-date-clone': 'warn',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-existence-index-check': 'warn',
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-abusive-eslint-disable': 'error',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-array-callback-reference': 'error',
    'unicorn/no-array-method-this-argument': 'warn',
    'unicorn/no-array-reverse': 'error',
    'unicorn/no-array-sort': 'error',
    'unicorn/no-array-for-each': 'error',
    'unicorn/no-await-expression-member': 'warn',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-hex-escape': 'warn',
    'unicorn/no-immediate-mutation': 'error',
    'unicorn/no-instanceof-builtins': 'warn',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-single-promise-in-promise-methods': 'warn',
    'unicorn/no-static-only-class': 'warn',
    'unicorn/no-thenable': 'error',
    'unicorn/no-this-assignment': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/no-unreadable-iife': 'warn',
    'unicorn/no-useless-collection-argument': 'warn',
    'unicorn/no-useless-error-capture-stack-trace': 'warn',
    'unicorn/no-useless-fallback-in-spread': 'warn',
    'unicorn/no-useless-length-check': 'warn',
    'unicorn/no-useless-promise-resolve-reject': 'warn',
    'unicorn/no-useless-spread': 'warn',
    'unicorn/no-useless-switch-case': 'warn',
    'unicorn/no-useless-undefined': 'warn',
    'unicorn/no-zero-fractions': 'warn',
    'unicorn/number-literal-case': 'warn',
    'unicorn/numeric-separators-style': 'warn',
    'unicorn/prefer-array-find': 'warn',
    'unicorn/prefer-array-flat': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/prefer-array-some': 'warn',
    'unicorn/prefer-at': 'warn',
    'unicorn/prefer-code-point': 'warn',
    'unicorn/prefer-date-now': 'warn',
    'unicorn/prefer-default-parameters': 'warn',
    'unicorn/prefer-global-this': 'warn',
    'unicorn/prefer-includes': 'warn',
    'unicorn/prefer-logical-operator-over-ternary': 'warn',
    'unicorn/prefer-math-min-max': 'warn',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-modern-math-apis': 'warn',
    'unicorn/prefer-native-coercion-functions': 'warn',
    'unicorn/prefer-negative-index': 'warn',
    'unicorn/prefer-number-properties': 'warn',
    'unicorn/prefer-object-from-entries': 'warn',
    'unicorn/prefer-set-has': 'warn',
    'unicorn/prefer-set-size': 'warn',
    'unicorn/prefer-spread': 'warn',
    'unicorn/prefer-string-replace-all': 'warn',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-string-starts-ends-with': 'warn',
    'unicorn/prefer-string-trim-start-end': 'warn',
    'unicorn/prefer-structured-clone': 'warn',
    'unicorn/prefer-top-level-await': 'warn',
    'unicorn/relative-url-style': 'warn',
    'unicorn/require-array-join-separator': 'warn',
    'unicorn/require-number-to-fixed-digits-argument': 'warn',
    'unicorn/text-encoding-identifier-case': 'warn',
    'unicorn/throw-new-error': 'warn',
    'unicorn/prefer-class-fields': 'warn',
    'unicorn/prefer-blob-reading-methods': 'warn',
    'unicorn/prefer-response-static-json': 'warn'
    // unicorn/better-regex — not available in OxLint, stays ESLint-only
};
