/**
 * @fileoverview Regex rules for OxLint (eslint-plugin-regexp)
 *
 * Maps to eslint/rules/regexp.js.
 * Loaded via jsPlugins (eslint-plugin-regexp).
 * ReDoS protection, optimization, validity checks.
 */

export const regexp = {
    'regexp/no-invalid-regexp': 'warn',
    'regexp/no-empty-character-class': 'warn',
    'regexp/no-control-character': 'warn',
    'regexp/strict': 'warn',
    'regexp/no-empty-alternative': 'warn',
    'regexp/no-empty-capturing-group': 'warn',
    'regexp/no-empty-group': 'warn',
    'regexp/no-empty-lookarounds-assertion': 'warn',
    'regexp/no-contradiction-with-assertion': 'warn',
    'regexp/no-optional-assertion': 'warn',
    'regexp/no-useless-assertions': 'warn',
    'regexp/no-useless-backreference': 'warn',
    'regexp/no-potentially-useless-backreference': 'warn',
    'regexp/no-super-linear-backtracking': 'error',
    'regexp/no-misleading-capturing-group': 'warn',
    'regexp/no-misleading-unicode-character': 'warn',
    'regexp/no-missing-g-flag': 'warn',
    'regexp/no-dupe-disjunctions': 'warn',
    'regexp/no-escape-backspace': 'warn',
    'regexp/no-useless-dollar-replacements': 'warn',
    'regexp/no-lazy-ends': 'warn',
    'regexp/no-dupe-characters-character-class': 'warn',
    'regexp/no-useless-character-class': 'warn',
    'regexp/no-useless-lazy': 'warn',
    'regexp/no-useless-quantifier': 'warn',
    'regexp/no-useless-range': 'warn',
    'regexp/no-useless-two-nums-quantifier': 'warn',
    'regexp/no-useless-flag': 'warn',
    'regexp/no-trivially-nested-quantifier': 'warn',
    'regexp/no-trivially-nested-assertion': 'warn',
    'regexp/optimal-quantifier-concatenation': 'warn',
    'regexp/no-legacy-features': 'warn',
    'regexp/no-non-standard-flag': 'warn',
    'regexp/no-obscure-range': 'warn',
    'regexp/no-invisible-character': 'warn',
    'regexp/no-empty-string-literal': 'warn',
    'regexp/no-extra-lookaround-assertions': 'warn',
    'regexp/confusing-quantifier': 'warn',
    'regexp/optimal-lookaround-quantifier': 'warn',
    'regexp/control-character-escape': 'warn',
    'regexp/negation': 'warn',
    'regexp/no-unused-capturing-group': 'warn',
    'regexp/no-zero-quantifier': 'warn',
    'regexp/no-useless-set-operand': 'warn',
    'regexp/no-useless-string-literal': 'warn',
    'regexp/prefer-predefined-assertion': 'warn',
    'regexp/match-any': 'warn',
    'regexp/no-useless-escape': 'warn',
    'regexp/no-useless-non-capturing-group': 'warn',
    'regexp/prefer-character-class': 'warn',
    'regexp/prefer-d': 'warn',
    'regexp/prefer-w': 'warn',
    'regexp/prefer-plus-quantifier': 'warn',
    'regexp/prefer-question-quantifier': 'warn',
    'regexp/prefer-star-quantifier': 'warn',
    'regexp/prefer-unicode-codepoint-escapes': 'warn',
    'regexp/prefer-range': 'warn',
    'regexp/prefer-set-operation': 'warn',
    'regexp/simplify-set-operations': 'warn',
    'regexp/sort-flags': 'warn',
    'regexp/use-ignore-case': 'warn'
};
